include:
  - modules.base
  - modules.ssh
  - modules.ufw
  - modules.nginx
  - modules.redis
  - modules.memcached
  - modules.supervisor
  - modules.beanstalkd
  - modules.monit
  - modules.nullmailer
  - modules.s3cmd
  - modules.sites
